# 4 Different Ways to Multiply 2 Matrices

Let's establish a simple toy example as a baseline first:

In [1]:
import numpy as np

A = np.array([[1.1, 1.2, 1.3],
              [2.4, 2.5, 2.6],
              [3.7, 3.8, 3.9]])

B = np.array([[4.1, 4.2, 4.3],
              [5.4, 5.5, 5.6],
              [6.7, 6.8, 6.9]])

In [2]:
A @ B

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])

## 1) Compute row-column dot-products (the conventional way)

Each element A[i, j] in the resulting matrix A.B = AB is a dot product of row A[i, ] and column B[, j].

In [3]:
AB = np.zeros((A.shape[0], B.shape[1]))

for i, row in enumerate(A):
    for j, column in enumerate(B.T):
        AB[i, j] = row.dot(column)

AB

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])

## 2) Row-vectors times matrix

For each column B[, j], compute the dot products between A and B[, j] to get the resulting column AB[, j].

For each row A[i, ], compute the dot products with B to get the resulting row AB[i, ].

In [4]:
AB = np.zeros((A.shape[0], B.shape[1]))

for i, row in enumerate(A):
    AB[i] = row.dot(B)
    
AB

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])

## 3) Matrix times column-vectors

In [5]:
AB = np.zeros((A.shape[0], B.shape[1]))

for j, column in enumerate(B.T):
    AB[:, j] = A.dot(column[:, None]).flatten()
    
AB

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])

## 4) Columns times rows

## 4.1) Columns times rows with dot products (matmuls)

This procedure works for square matrices only:

- Compute the dot-products between the columns in A and rows in B. 
- If A is $m\times n$-dimensional, each dot-product is a $m\times n$-dimensional matrix
- Then sum these matrices

In [6]:
AB = np.zeros((A.shape[1], B.shape[0]))

for column_A, row_B in zip(A.T, B):
    AB += column_A[:, None].dot(row_B[None, :])
    
AB

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])

## 4.2) Columns times rows with outer products

For each row in A and each column in B, compute the outer product. 
The matrix AB is the sum over all these outer products.

In [7]:
AB = np.zeros((A.shape[0], B.shape[1]))

for column_A, row_B in zip(A.T, B):
    AB += np.outer(column_A, row_B)
    
AB

array([[19.7 , 20.06, 20.42],
       [40.76, 41.51, 42.26],
       [61.82, 62.96, 64.1 ]])

## Bonus: The 5th way -- Block multiplication

In block multiplication, we can divide up a large matrix into smaller blocks and then multiply them separately.

Suppose we have the following matrix multiplication

$$
A=\begin{bmatrix}
1.1 & 1.2 & 1.3 & 1.4\\
2.1 & 2.2 & 2.3 & 2.4\\
3.1 & 3.2 & 3.3 & 3.4\\
4.1 & 4.2 & 4.3 & 4.4
\end{bmatrix}
B=\begin{bmatrix}
5.1 & 5.2 & 5.3 & 5.4\\
6.1 & 6.2 & 6.3 & 6.4\\
7.1 & 7.2 & 7.3 & 7.4\\
8.1 & 8.2 & 8.3 & 8.4
\end{bmatrix}
$$

$$
AB=\begin{bmatrix}
33.5 & 34.0 & 34.5 & 35.0\\
59.9 & 60.8 & 61.7 & 62.6\\
86.3 & 87.6 & 88.9 & 90.2\\
112.7 & 114.4 & 116.1 & 117.8
\end{bmatrix}
$$

The multiplication of the blocks looks as follows:

$$
A = \left[\begin{array}{ll}
A_1 & A_2 \\
A_3 & A_4
\end{array}\right]
B = \left[\begin{array}{ll}
B_1 & B_2 \\
B_3 & B_4
\end{array}\right] \\ 
AB =
\left[\begin{array}{ll} A_1 B_1+A_2 B_3 & A_1 B_2+A_2 B_4 \\
A_3 B_1+A_4 B_3 & A_3 B_2+A_4 B_4
\end{array}\right]
$$

In [8]:
A = np.array([[1.1, 1.2, 1.3, 1.4],
              [2.1, 2.2, 2.3, 2.4],
              [3.1, 3.2, 3.3, 3.4],
              [4.1, 4.2, 4.3, 4.4]])

B = np.array([[5.1, 5.2, 5.3, 5.4],
              [6.1, 6.2, 6.3, 6.4],
              [7.1, 7.2, 7.3, 7.4],
              [8.1, 8.2, 8.3, 8.4]])

In [9]:
A @ B

array([[ 33.5,  34. ,  34.5,  35. ],
       [ 59.9,  60.8,  61.7,  62.6],
       [ 86.3,  87.6,  88.9,  90.2],
       [112.7, 114.4, 116.1, 117.8]])

In [10]:
A1, A2 = A[:2, :2], A[:2, 2:]
A3, A4 = A[2:, :2], A[2:, 2:]

B1, B2 = B[:2, :2], B[:2, 2:]
B3, B4 = B[2:, :2], B[2:, 2:]

In [11]:
C1, C2 = A1@B1 + A2@B3, A1@B2 + A2@B4
C3, C4 = A3@B1 + A4@B3, A3@B2 + A4@B4

In [12]:
AB = np.vstack((np.hstack((C1, C2)),
                np.hstack((C3, C4))))

AB

array([[ 33.5,  34. ,  34.5,  35. ],
       [ 59.9,  60.8,  61.7,  62.6],
       [ 86.3,  87.6,  88.9,  90.2],
       [112.7, 114.4, 116.1, 117.8]])